name: sisppeo

channels:
  - conda-forge
  - defaults
  
dependencies:
  - python=3.8
  - pip
  - affine
  - click
  - colorcet
  - datashader
  - fiona
  - lxml
  - matplotlib-base
  - netcdf4
  - numpy
  - pandas
  - pillow
  - plotly
  - psutil
  - pvlib-python
  - pyproj
  - pyyaml
  - rasterio
  - ray-core
  - s2cloudless
  - scikit-image
  - scikit-learn
  - scipy
  - shapely
  - tqdm
  - xarray

