ndvi:
  long_name: Normalized Difference Vegetation Index
  output: ndvi
  L4:
    - B3
    - B4
  L5:
    - B3
    - B4
  L7:
    - B3
    - B4
  L8:
    - B4
    - B5
  S2:
    - B4
    - B8
nbr:
  long_name: Normalized Burn Ratio
  output: nbr
  L8:
    - B7
    - B5
  S2:
    - B12
    - B8
