s2cloudless:
  long_name:
    - Cloud mask (Sentinel Hub's cloud detector for Sentinel-2 imagery)
    - Cloud probabilities (Sentinel Hub's cloud detector for Sentinel-2 imagery)
  output: [clm, clp]
  S2:
    - B1
    - B2
    - B4
    - B5
    - B8
    - B8A
    - B9
    - B10
    - B11
    - B12
waterdetect:
  long_name: Water mask (WaterDetect; OBS2CO) from Cordeiro, Martinez and Peña-Luque (2021).
  output: wm
  L8:
    - B3
    - B5
    - B6
    - B7
  S2:
    - B3
    - B8
    - B11
    - B12